apiVersion: v1
kind: ReplicationController
metadata:
  name: hellonode.controller
spec:
  replicas: 2
  selector:
    app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
        - name: hellonode-demo
          image: gomn/hellonode
          ports:
            - containerPort: 3000
    
