apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
        - name: hellonode-demo
          image: gomn/hellonode
          ports:
            - name: nodejs-port
              containerPort: 3000
    
